name: event_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.0
  flutter_hooks: ^0.20.1
  get_it: ^7.6.4
  flutter_screenutil: ^5.9.0
  dio: ^5.3.2
  oktoast: ^3.3.1
  image_picker: ^1.0.4
  flutter_secure_storage: ^9.0.0
  intl: ^0.18.1
  flutter_svg: ^2.0.7
  iconsax: ^0.0.8
  google_sign_in: ^6.1.5

flutter_native_splash:
  android: true
  ios: true
  color: "#28289F"
  image: "assets/images/splashscreen.png"
  android_12:
    image: "assets/images/splashscreen.png"

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  stacked_generator: ^1.5.1

flutter:
  uses-material-design: true

  assets:
    - assets/svgs/
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins-ExtraLight.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Thin.ttf

  #   - family: Raleway
  #     fonts:
  #      - asset: assets/fonts/Raleway.ttf
