name: event_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:

  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter

    # They exist for one reason: increase the code-sharing between widgets by removing duplicates.
  flutter_hooks: ^0.18.6


   # A flutter plugin for adapting screen and font size.Let your UI display a reasonable layout on different screen sizes!
  flutter_screenutil: ^5.9.0
  
   # Provides internationalization and localization facilities,
  http: ^1.1.0
  intl: ^0.18.1

   # Logging info to the console  
  json_annotation: ^4.8.1
  logger: ^1.1.2

   # Provider state management library extension with classes to boost mvvm architecture
  stacked: ^3.4.1+1

  #App splashscreen
  flutter_native_splash: ^2.3.2
  
  stacked_hooks: ^0.2.3
  stacked_services: ^1.3.0


flutter_native_splash:
  android: true
  ios: true
  color: '#28289F'
  image: 'assets/images/splashscreen.png'
  android_12:
    image: 'assets/images/splashscreen.png'


dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  stacked_generator: ^1.5.1
  json_serializable: ^6.7.1
  build_runner: ^2.4.6

flutter:

  uses-material-design: true

  assets:
    
    - assets/svgs/
    - assets/images/
    - assets/fonts/
   


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins-ExtraLight.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Thin.ttf

 #   - family: Raleway
 #     fonts:
  #      - asset: assets/fonts/Raleway.ttf