// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANkMX3FfHn3rglKA3mMHy4IswC5KkYcPY',
    appId: '1:155181837869:android:5c071791bd74643fc1d2a4',
    messagingSenderId: '155181837869',
    projectId: 'vikings-event-mobile',
    storageBucket: 'vikings-event-mobile.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0sZIbKPVQbuDohvwTYl08gB9I-AQ9Fc0',
    appId: '1:155181837869:ios:958a873f321316f3c1d2a4',
    messagingSenderId: '155181837869',
    projectId: 'vikings-event-mobile',
    storageBucket: 'vikings-event-mobile.appspot.com',
    androidClientId: '155181837869-5424bfflj6rve1htbsa4sc8k61gurvrv.apps.googleusercontent.com',
    iosClientId: '155181837869-7s5b7po5i25uqv0g13fcosa3ru7vjv9a.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventApp',
  );
}
